### PR TITLE
Remove obsolete buildID system

### PR DESCRIPTION
**Pull request by olekw**
The __TIME__ and __DATE__ macros were interfering with reproducible builds.

### CODE REVIEW

**Comment by olekw** [comment]
Erik,

This is building correctly on my system (using hammer). I've gone through the code pretty carefully and I'm pretty sure that I caught every related code fragment. Please let me know what you think. Thanks!

-Olek

**Comment by erikogenvik** [comment]
Did the buildId also make the builds non-repeatable?
Date and time aren't needed, but buildId being based on the commit SHA1 would serve some purpose. If it can be retained while still making builds repeatable I would prefer that.

**Comment by olekw** [comment]
Hmm, that's a good point! That shouldn't present a repeatability problem. Let me re-look at this commit..

**Comment by olekw** [comment]
Ok, I've removed the problematic date/time macros but retained the buildID code. I also cleaned up the buildID code a bit. It now produces correct result both in a Git repository as well as outside one. The latter case is what we would see when Cyphesis is built from a released source tar by a third party such as Debian or Fedora.

**Pull request merged**
